# Generated by Django 5.1 on 2024-08-30 07:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "hackathons",
            "0005_hackathon_registration_close_gte_registration_open_and_more",
        ),
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="team",
            unique_together={("hackathon", "leader")},
        ),
    ]
