# Generated by Django 5.1 on 2024-09-21 16:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0002_team_registered"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="registered",
            new_name="registration_complete",
        ),
    ]
