# Generated by Django 5.1 on 2024-08-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hackathons", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hackathon",
            name="end_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="hackathon",
            name="registrationClose",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="hackathon",
            name="registrationOpen",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="hackathon",
            name="start_date",
            field=models.DateTimeField(),
        ),
    ]
