# Generated by Django 5.1 on 2024-08-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hackathons", "0003_alter_hackathon_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hackathon",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hackathon",
            name="photo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="hackathon",
            name="subtitle",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
