# Generated by Django 5.1 on 2024-08-24 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "hackathons",
            "0004_alter_hackathon_description_alter_hackathon_photo_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="hackathon",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("registrationClose__gte", models.F("registrationOpen"))
                ),
                name="registration_close_gte_registration_open",
            ),
        ),
        migrations.AddConstraint(
            model_name="hackathon",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))),
                name="end_date_gte_start_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="hackathon",
            constraint=models.CheckConstraint(
                condition=models.Q(("maxTeamSize__gte", models.F("minTeamSize"))),
                name="max_team_size_gte_min_team_size",
            ),
        ),
    ]
