# Generated by Django 5.1 on 2024-08-23 08:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("syntaq_auth", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customusermodel",
            old_name="firstName",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="customusermodel",
            old_name="lastName",
            new_name="last_name",
        ),
    ]
